### ISSUE TITLE
add-team-label: Use `GITHUB_TOKEN` for authentication

### ISSUE THREAD

**Issue by legobeat** [MetaMask/github-tools#25]
The `add-team-label` workflow introduced in #23 both:
1. Expects the `PERSONAL_ACCESS_TOKEN` secret as configuration for GH PAT (instead of more common `GITHUB_TOKEN`)
    - This makes integration cumbersome. It would be great if `GITHUB_TOKEN` could be recognized.
2. Sets the token as `PERSONAL_ACCESS_TOKEN` to the `yarn run add-team-label` script.
    - Related: #24

It seems like there should only be one token needed for this workflow? And that in any case it needn't be exposed to any untrusted code?

**Comment by itsyoboieltr** [comment]
Hi @legobeat! Thank you for creating this issue. We needed to go with the `PERSONAL_ACCESS_TOKEN` instead of the usually preferred `GITHUB_TOKEN`, as the GitHub token only allows read operations within the repository that is running the GitHub action. During the action, wherever it runs, we would like to access the `MetaMask-planning` repository, to get the `teams.json` file. For this, we need to use `PERSONAL_ACCESS_TOKEN`.
